server:
  port: 8083 # Port du microservice

spring:
  application:
    name: UserAuthService
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    config:
      enabled: false


#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8761/eureka/
  #instance:
   # prefer-ip-address: true
eureka:
  client:
    enabled: false # Désactive l'enregistrement auprès du serveur Eureka
    register-with-eureka: false # Empêche l'enregistrement
    fetch-registry: false # Empêche de chercher le registre

logging:
  level:
    root: INFO



