
spring:
  application:
    name: UserAuthService
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.web: DEBUG
    com.netflix.discovery.shared.resolver.aws: ERROR