server:
  port: 8084

spring:
  application:
    name: ChallengesService
  datasource:
    url: jdbc:mysql://localhost:3306/challenges_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    enabled: false # Désactive l'enregistrement auprès du serveur Eureka
    register-with-eureka: false # Empêche l'enregistrement
    fetch-registry: false # Empêche de chercher le registre

spring.cloud.config:
  enabled: false # Désactive l'utilisation de ConfigClient

logging:
  level:
    root: INFO